### PR TITLE
SystemUI: Separate double tap to sleep on lockscreen

### PR DESCRIPTION
**Pull request by vherawidatama**
* fix bug input pin on lockscreen about dt2s

reff : https://github.com/Evolution-X/frameworks_base/commit/e94b68609ec42baa4b8ba625baf8afa3f3146f61

Notes : when user enters pin, triggers double tap to sleep on lock screen.

### CODE REVIEW

**Comment by Saikrishna1504** [comment]
Tested ?

**Comment by vherawidatama** [comment]
yes, tested on my device. Xiaomi 12 Lite aka Taoyao

**Comment by shutter-cat** [comment]
Will it disable the separate double tap function for sleep on the lock screen and status bar?

**Comment by vherawidatama** [comment]
Not sir, it function still work. Only validation when user input pin on lockscreen. Cause, on my device have problem when user input pin, The lockscreen should be open, but instead the screen sleeps when the user enters the PIN

**Pull request merged**
